create table senhas (
    id_usuario number(10) primary key,
    nome_usuario varchar2(50) not null,
    senha varchar2(255) not null,
    data_ultima_modificacao date
);

create table auditoria_senhas (
    id_auditoria number generated by default as identity primary key,
    id_usuario number(10),
    usuario_modificador varchar2(50),
    senha_antiga varchar2(255),
    senha_nova varchar2(255),
    data_modificacao timestamp
);

create or replace trigger trg_auditoria_senhas
after update of senha on senhas
for each row
begin
    if :old.senha != :new.senha then
        insert into auditoria_senhas (
            id_usuario,
            usuario_modificador,
            senha_antiga,
            senha_nova,
            data_modificacao
        ) values (
            :new.id_usuario,
            sys_context('userenv', 'os_user'),
            :old.senha,
            :new.senha,
            systimestamp
        );
    end if;
end;
/

set serveroutput on;

declare
    v_user_id number := 101;
    v_username varchar2(50) := 'fulano.teste';
    v_senha_antiga varchar2(255) := 'senha_inicial_123';
    v_senha_nova varchar2(255) := 'senha_nova_segura_456';
    v_audit_count number;
begin
    delete from auditoria_senhas where id_usuario = v_user_id;
    delete from senhas where id_usuario = v_user_id;

    dbms_output.put_line('dados de teste limpos.');

    insert into senhas (id_usuario, nome_usuario, senha, data_ultima_modificacao)
    values (v_user_id, v_username, v_senha_antiga, sysdate);
    
    commit;
    
    dbms_output.put_line('usuario ' || v_username || ' inserido com sucesso.');

    update senhas
    set senha = v_senha_nova
    where id_usuario = v_user_id;

    commit;
    
    dbms_output.put_line('senha do usuario ' || v_username || ' atualizada. verificando auditoria...');

    select count(*) into v_audit_count
    from auditoria_senhas
    where id_usuario = v_user_id
    and senha_antiga = v_senha_antiga
    and senha_nova = v_senha_nova;

    if v_audit_count = 1 then
        dbms_output.put_line('sucesso: a alteracao de senha foi auditada corretamente.');
    else
        dbms_output.put_line('falha: a alteracao de senha nao foi auditada como esperado.');
    end if;

    delete from auditoria_senhas where id_usuario = v_user_id;
    delete from senhas where id_usuario = v_user_id;
    
    commit;
    
    dbms_output.put_line('dados de teste removidos.');

exception
    when others then
        rollback;
        dbms_output.put_line('ocorreu um erro: ' || sqlerrm);
end;
/